### ISSUE TITLE
nginx missing from docker built on repo

### ISSUE THREAD

**Issue by borisski** [peering-manager/docker#16]
Hello,
I pull docker image built from the repo, I got 404 for all the REQ toward /static/* , I had to log into the container ,apt install nginx and copy /etc/peering-manager/nginx/nginx.conf to /etc/nginx/nginx.conf. Not sure I'm doing it the right way. Anyway it seems that sth was missing

**Comment by gmazoyer** [comment]
nginx is not in the base image itself but setup with the docker-compose file. Can someone confirm this, just so I know I don't say something wrong?

**Comment by jamesditrapani** [comment]
> nginx is not in the base image itself but setup with the docker-compose file. Can someone confirm this, just so I know I don't say something wrong?

This is correct. Nginx is a part of the compose build along with redis, postgres & the worker.

Example from my `peering-manager-compose.yaml`
```
  peering-manager-nginx:
    image: nginx:1.17-alpine
    command: nginx -c /etc/peering-manager/nginx/nginx.conf
    depends_on:
      - peering-manager
    ports:
      - 8080:8080
    volumes:
      - peering-manager-static-files:/opt/peering-manager/static:ro
      - peering-manager-nginx-config:/etc/peering-manager/nginx:ro
    networks:
      - peering-manager
```
